default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres
  database: chytonpide
  port: 5432

development:
  <<: *default
  database: chytonpide_development

test:
  <<: *default
  database: chytonpide_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["APPSETTING_DB_HOST"] %>
    username: <%= ENV["APPSETTING_DB_USER"] %>
    password: <%= ENV["APPSETTING_DB_PASSWORD"] %>
    database: <%= ENV["APPSETTING_DB_NAME"] %>
