default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres
  database: chytonpide
  port: 5432

development:
  <<: *default
  database: chytonpide_development

test:
  <<: *default
  database: chytonpide_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["APPSETTING_DB_HOST"] %>
    username: <%= ENV["APPSETTING_DB_USER"] %>
    password: <%= ENV["APPSETTING_DB_PASSWORD"] %>
    database: <%= ENV["APPSETTING_DB_NAME"] %>
  cache:
    <<: *primary_production
    database: chytonpide_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: chytonpide_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: chytonpide_production_cable
    migrations_paths: db/cable_migrate